import About from "./components/aboutme/About";
import MySkills from "./components/myskills/MySkills";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import Providers from "./provides";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <About />
          <MySkills />
        </Providers>
      </body>
    </html>
  );
}
